### ISSUE TITLE
[BUG] Cudf Read Parquet from Dask delayed copies data to GPU0 after operation

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/dask-cudf#225]
I have a cluster and I'm using Dask delayed with cudf's read_parquet to read a parquet file. Dask cudf tries to read the file on one GPU and then transfer the data to GPU0. 
Also if by chance the worker reading the file also happens to be on GPU0, it then tries to transfer this data to the other python instance of GPU0 as shown in `nvidia-smi`. 

This new data on GPU0,  occasionally gets garbage collected randomly later when executing other commands.

I have attached a gif that demonstrates the issue. (Sorry for the bad resolution might need to zoom in)

Example:
```
from dask.distributed import Client, wait
from dask_cuda import LocalCUDACluster
import dask, dask_cudf
cluster = LocalCUDACluster(ip='0.0.0.0')
client = Client(cluster)

import pandas as pd
import numpy as np
df = pd.DataFrame({'Col1':['a','b']*85000000,'Col2':np.random.randint(100,size=170_000_000)})
df.to_parquet('temp.snappy.parquet')

import cudf
parts = [dask.delayed(cudf.io.parquet.read_parquet)
         (path='temp.snappy.parquet')]
ddf = dask_cudf.from_delayed(parts)
```
![example](https://user-images.githubusercontent.com/19949207/57173033-b4cc5200-6ddd-11e9-868f-cf7f6fb8140e.gif)

**Comment by mrocklin** [comment]
> Dask cudf tries to read the file on one GPU and then transfer the data to GPU0

My guess is that this comes from this line: 

    ddf = dask_cudf.from_delayed(parts)

It doesn't know the columns or dtypes (the meta) so it has to run one of your tasks to get a sample dataframe, and then it brings that back to the client so that your dask dataframe can have the right columns and dtypes.

Typically this is solved by reading the metadata in the parquet files themselves, which avoids having to read any significant data.  For this though we would need more logic.  This is one of the things that the proper `dd.read_parquet` function does (though currently only for CPU data).

> This new data on GPU0, occasionally gets garbage collected randomly later when executing other commands.

This seems reasonable to me.  We don't need the data around at this stage, only the columns and dtypes.

**Comment by mrocklin** [comment]
OK to close @ayushdg ?

**Comment by ayushdg** [comment]
> It doesn't know the columns or dtypes (the meta) so it has to run one of your tasks to get a sample dataframe, and then it brings that back to the client so that your dask dataframe can have the right columns and dtypes.
> 
Hey @mrocklin. I'm still a bit unsure about what this means. My understanding is that dask does not know what my metadata looks like so it has to run one of the tasks to get a sample Dataframe. Assuming dask does this on GPU-3. It performs the task infers the metadata etc. I'm still not sure why there is a transfer of this Dataframe back to GPU0. It would be great if you could elaborate a bit on this.

**Comment by mrocklin** [comment]
> I'm still a bit unsure about what this means. My understanding is that dask does not know what my metadata looks like so it has to run one of the tasks to get a sample Dataframe. 

Yes, exactly

> Assuming dask does this on GPU-3. It performs the task infers the metadata etc. I'm still not sure why there is a transfer of this Dataframe back to GPU0

It stores the metadata as a tiny cudf dataframe, so it has to move some data back to where the Dask dataframe lives.  Currently it looks like it moves the full partition, and then calls head.  Probably it should call head and then move that.

**Comment by mrocklin** [comment]
https://github.com/dask/dask/pull/4802
